FROM nginx

#  Set the working directory
WORKDIR /app/

#  Copy nginx app site config
COPY app /app/

#  Copy custom server config
COPY nginx.conf /etc/nginx/nginx.conf

#  Move and link site config
#  See: https://stackoverflow.com/questions/17413526/nginx-missing-sites-available-directory
RUN mkdir /etc/nginx/sites-enabled/
RUN mkdir /etc/nginx/sites-available/
RUN cp app /etc/nginx/sites-available/
RUN ln -s /etc/nginx/sites-available/app /etc/nginx/sites-enabled/app

# keep server in foreground and prevent container close
CMD ["nginx", "-g", "daemon off;"]
